# Generated by Django 3.2.8 on 2021-12-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssMonitoringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'ess_monitoring_log',
                'managed': False,
            },
        ),
    ]
