steps:
# Install dependencies And Run tests
- name: 'python:3.8-slim'
  id: Test
  entrypoint: /bin/sh
  args: 
  - -c
  - 'pip install -r requirements.txt && python manage.py test --keepdb'
  env:
  - 'DJANGO_SETTINGS_MODULE=${_DJANGO_SETTINGS_MODULE}'
  - 'SECRET_KEY=${_SECRET_KEY}'
  - 'DEFAULT_DB_ENGINE=${_DEFAULT_DB_ENGINE}'
  - 'DEFAULT_DB_HOST=${_DEFAULT_DB_HOST}'
  - 'DEFAULT_DB_PORT=${_DEFAULT_DB_PORT}'
  - 'DEFAULT_DB_NAME=${_DEFAULT_DB_NAME}'
  - 'DEFAULT_DB_USER=${_DEFAULT_DB_USER}'
  - 'DEFAULT_DB_PASSWORD=${_DEFAULT_DB_PASSWORD}'
  - 'DEFAULT_TEST_DB_NAME=${_DEFAULT_TEST_DB_NAME}'
  - 'ESS_DB_ENGINE=${_ESS_DB_ENGINE}'
  - 'ESS_DB_HOST=${_ESS_DB_HOST}'
  - 'ESS_DB_PORT=${_ESS_DB_PORT}'
  - 'ESS_DB_NAME=${_ESS_DB_NAME}'
  - 'ESS_DB_USER=${_ESS_DB_USER}'
  - 'ESS_DB_PASSWORD=${_ESS_DB_PASSWORD}'
  - 'ESS_TEST_DB_NAME=${_ESS_TEST_DB_NAME}'

# Docker build
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/ess-dataplatform-web-repository/ess-dataplatform-web:${SHORT_SHA}', '.']

# Docker push to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args: ['push', 'asia-northeast3-docker.pkg.dev/${PROJECT_ID}/ess-dataplatform-web-repository/ess-dataplatform-web:${SHORT_SHA}']