# Generated by Django 3.2.8 on 2022-07-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastingBankSoL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('operating_site', models.IntegerField(db_column='operating_site_id')),
                ('bank_id', models.IntegerField(db_column='bank_id')),
                ('forecasting_sol', models.FloatField(db_column='forecasting_sol')),
                ('forecasting_sol_top_limit', models.FloatField(db_column='forecasting_sol_top_limit', null=True)),
                ('forecasting_sol_bottom_limit', models.FloatField(db_column='forecasting_sol_bottom_limit', null=True)),
            ],
            options={
                'db_table': 'forecasting_bank_sol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectionMapErrorCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'protectionmap_error_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectionMapFeature',
            fields=[
                ('timestamp', models.DateTimeField(db_column='TIMESTAMP', primary_key=True, serialize=False)),
                ('bank_id', models.IntegerField(db_column='BANK_ID')),
                ('rack_id', models.IntegerField(db_column='RACK_ID')),
                ('operating_site', models.IntegerField(db_column='OPERATING_SITE')),
            ],
            options={
                'db_table': 'protectionmap_feature',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProtectionMapLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'protectionmap_level',
                'managed': False,
            },
        ),
    ]
