# Generated by Django 3.2.8 on 2022-08-26 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess_feature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtectionMapFeatureTest',
            fields=[
                ('timestamp', models.DateTimeField(db_column='TIMESTAMP', primary_key=True, serialize=False)),
                ('bank_id', models.IntegerField(db_column='BANK_ID')),
                ('rack_id', models.IntegerField(db_column='RACK_ID')),
                ('operating_site', models.IntegerField(db_column='OPERATING_SITE')),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=300, null=True)),
            ],
            options={
                'db_table': 'protectionmap_feature_new_test',
                'managed': False,
            },
        ),
    ]
