# Generated by Django 3.2.8 on 2022-08-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ess_feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='protectionmapfeature',
            table='protectionmap_feature_new',
        ),
    ]
