# Generated by Django 3.2.8 on 2022-08-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvgBankSoH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_site', models.IntegerField(db_column='operating_site_id')),
                ('bank_id', models.IntegerField()),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'avg_bank_soh',
            },
        ),
        migrations.AddConstraint(
            model_name='avgbanksoh',
            constraint=models.UniqueConstraint(fields=('operating_site', 'bank_id', 'date'), name='avg_bank_soh_unique'),
        ),
    ]
