# Generated by Django 3.2.8 on 2022-08-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess_stats', '0004_auto_20220808_1735'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForecastingRackMaxCellVoltage',
            new_name='ForecastingMaxRackCellVoltage',
        ),
        migrations.RemoveConstraint(
            model_name='forecastingmaxrackcellvoltage',
            name='forecasting_rack_max_cell_voltage_unique',
        ),
        migrations.AddConstraint(
            model_name='forecastingmaxrackcellvoltage',
            constraint=models.UniqueConstraint(fields=('operating_site', 'bank_id', 'rack_id', 'time'), name='forecasting_max_rack_cell_voltage_unique'),
        ),
        migrations.AlterModelTable(
            name='forecastingmaxrackcellvoltage',
            table='forecasting_max_rack_cell_voltage',
        ),
    ]
