# Generated by Django 3.2.8 on 2022-08-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ess_stats", "0006_auto_20220818_1724"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastingMaxRackCellTemperature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("operating_site", models.IntegerField(db_column="operating_site_id")),
                ("bank_id", models.IntegerField()),
                ("rack_id", models.IntegerField()),
                ("time", models.DateTimeField()),
                ("values", models.JSONField()),
            ],
            options={
                "db_table": "forecasting_max_rack_cell_temperature",
            },
        ),
        migrations.AddConstraint(
            model_name="forecastingmaxrackcelltemperature",
            constraint=models.UniqueConstraint(
                fields=("operating_site", "bank_id", "rack_id", "time"),
                name="forecasting_max_rack_cell_temperature_unique",
            ),
        ),
    ]
