# Generated by Django 3.2.8 on 2022-10-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess_stats', '0008_auto_20220822_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoS',
            fields=[
                ('time', models.DateTimeField(db_column='TIMESTAMP', primary_key=True, serialize=False)),
                ('operating_site', models.IntegerField(db_column='OPERATING_SITE')),
                ('bank_id', models.IntegerField(db_column='BANK_ID')),
                ('rack_id', models.IntegerField(db_column='RACK_ID')),
                ('over_voltage', models.FloatField(db_column='OVER_VOLTAGE')),
                ('under_voltage', models.FloatField(db_column='UNDER_VOLTAGE')),
                ('voltage_unbalance', models.FloatField(db_column='VOLTAGE_UNBALANCE')),
                ('over_current', models.FloatField(db_column='OVER_CURRENT')),
                ('over_temperature', models.FloatField(db_column='OVER_TEMPERATURE')),
                ('under_temperature', models.FloatField(db_column='UNDER_TEMPERATURE')),
                ('temperature_unbalance', models.FloatField(db_column='TEMPERATURE_UNBALANCE')),
                ('sos_score', models.FloatField(db_column='SOS_SCORE')),
            ],
            options={
                'db_table': 'ess_sos',
                'managed': False,
            },
        ),
    ]
