# Generated by Django 3.2.8 on 2022-12-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess_stats', '0009_sos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExSoS',
            fields=[
                ('time', models.DateTimeField(db_column='TIMESTAMP', primary_key=True, serialize=False)),
                ('mode', models.IntegerField(db_column='MODE')),
                ('operating_site', models.IntegerField(db_column='OPERATING_SITE')),
                ('bank_id', models.IntegerField(db_column='BANK_ID')),
                ('rack_id', models.IntegerField(db_column='RACK_ID')),
                ('time_intervar', models.FloatField(db_column='TIME_INTERVAL')),
                ('integrated_safety', models.FloatField(db_column='INTEGRATED_SAFETY')),
            ],
            options={
                'db_table': 'ess_exsos',
                'managed': False,
            },
        ),
    ]
