# Generated by Django 3.2.8 on 2023-01-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ess_stats", "0009_sos"),
    ]

    operations = [
        migrations.CreateModel(
            name="EXSoS",
            fields=[
                ("time", models.DateTimeField(db_column="TIMESTAMP", primary_key=True, serialize=False)),
                ("mode", models.IntegerField(blank=True, db_column="MODE", null=True)),
                ("operating_site", models.IntegerField(blank=True, db_column="OPERATING_SITE", null=True)),
                ("bank_id", models.IntegerField(blank=True, db_column="BANK_ID", null=True)),
                ("rack_id", models.IntegerField(blank=True, db_column="RACK_ID", null=True)),
                ("integrated_safety", models.FloatField(blank=True, db_column="INTEGRATED_SAFETY", null=True)),
                ("membership_degree", models.TextField(blank=True, db_column="MEMBERSHIP_DEGREE", null=True)),
            ],
            options={
                "db_table": "ess_exsos",
                "managed": False,
            },
        ),
    ]
