# Generated by Django 3.2.8 on 2023-02-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess_stats', '0011_multistepforecastingmaxvoltage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiStepForecastingMaxCellVoltage',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('operating_site', models.IntegerField(blank=True, db_column='operating_site_id', null=True)),
                ('bank_id', models.IntegerField(blank=True, null=True)),
                ('rack_id', models.IntegerField(blank=True, null=True)),
                ('values', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'multi_step_forecasting_maxvol',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='MultiStepForecastingMaxVoltage',
        ),
    ]
