# Generated by Django 3.2.8 on 2023-02-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess_stats', '0012_auto_20230213_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('chart_type', models.CharField(max_length=150)),
                ('values', models.JSONField()),
            ],
        ),
    ]
