# Generated by Django 3.2.8 on 2023-02-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ess_stats', '0013_staticchartdata'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='staticchartdata',
            table='static_chart_data',
        ),
    ]
