# Generated by Django 3.2.8 on 2023-03-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess_stats', '0014_alter_staticchartdata_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastingSoS',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('operating_site', models.IntegerField(db_column='operating_site_id')),
                ('bank_id', models.IntegerField()),
                ('rack_id', models.IntegerField()),
                ('values', models.JSONField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'forecasting_rack_sos',
                'managed': False,
            },
        ),
    ]
