# Generated by Django 3.2.8 on 2023-04-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ess_stats', '0015_forecastingsos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forecastingmaxrackcelltemperature',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='forecastingmaxrackcellvoltage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='forecastingminrackcelltemperature',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='forecastingminrackcellvoltage',
            options={'managed': False},
        ),
    ]
