# Generated by Django 3.2.8 on 2023-06-11 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ess_stats', '0016_auto_20230410_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoCP',
            fields=[
                ('time', models.DateTimeField(db_column='TIMESTAMP', primary_key=True, serialize=False)),
                ('operating_site', models.IntegerField(blank=True, db_column='OPERATING_SITE', null=True)),
                ('bank_id', models.IntegerField(blank=True, db_column='BANK_ID', null=True)),
                ('rack_id', models.IntegerField(blank=True, db_column='RACK_ID', null=True)),
                ('period', models.IntegerField(blank=True, db_column='PERIOD', null=True)),
                ('charge_status', models.IntegerField(blank=True, db_column='CHARGE_STATUS', null=True)),
                ('soc_range', models.IntegerField(blank=True, db_column='SOC_RANGE', null=True)),
                ('value', models.TextField(blank=True, db_column='VALUE', null=True)),
            ],
            options={
                'db_table': 'ess_socp',
                'managed': False,
            },
        ),
    ]
